export default [
	require('./intro').default,
	require('./demo-vidkid-bouncing-circles').default,
	require('./demo-vidkid-drums-svg').default,
	require('./demo-vidkid-lazer-notes').default,
	require('./demo-vidkid-3d-cam').default,
	require('./wrong').default,
	require('./me').default,
	require('./demo-thank-you').default,
	require('./me-pic').default,
	require('./inspiration').default,
	require('./break-stuff').default,
	require('./break-stuff-lesson').default,
	require('./modular').default,
	require('./modular-2').default,
	require('./modular-takeaway').default,
	require('./album-art-generator').default,
	require('./lzx').default,
	// require('./idea.jsx').default,
	require('./modal').default,
	require('./atari').default,
	require('./devo').default,
	require('./video-modular-takeaway').default,
	require('./digital-vis-white').default,
	require('./digital-vis-black').default,
	require('./web-apis').default,
	require('./original-idea').default,
	require('./demo-vidkid-mouse-coords').default,

	require('./node-api').default,
	require('./vid-kid-screenshot').default,
	require('./vid-kid-explainer').default,
	require('./web-component').default,
	require('./web-component-2').default,
	require('./web-component-problems').default,
	require('./what-would-i-change').default,
	require('./final-lessons').default,
	require('./my-web-component').default,
	// Begin unsure zone:

	require('./midi-0').default,
	require('./midi-1').default,
	require('./midi-2').default,
	require('./midi-3').default,
	require('./midi-4').default,
	require('./midi-5').default,

	require('./how-its-made').default,

	require('./write-to-iframe').default,
	require('./demo-write-to-iframe').default,

	require('./eval').default,
	require('./eval-how-to').default,
	require('./eval-sandboxing').default,

	require('./not-original').default,
	require('./prior-art').default
]
