export default [
	require('./intro.jsx').default,
	require('./wrong').default,
	require('./me.jsx').default,
	require('./me-pic.jsx').default,
	require('./inspiration.jsx').default,
	require('./break-stuff.jsx').default,
	require('./break-stuff-lesson.jsx').default,

	require('./modular.jsx').default,
	require('./modular-2.jsx').default,
	require('./modular-takeaway.jsx').default,
	require('./album-art-generator.jsx').default,
	require('./lzx.jsx').default,
	// require('./idea.jsx').default,

	require('./modal.jsx').default,
	require('./atari.jsx').default,
	require('./devo.jsx').default,
	require('./video-modular-takeaway.jsx').default,
	require('./digital-vis-white.jsx').default,
	require('./digital-vis-black.jsx').default,
	require('./web-apis.jsx').default,
	require('./original-idea').default,
	require('./midi-0.jsx').default,
	require('./midi-1.jsx').default,
	require('./midi-2.jsx').default,
	require('./midi-3.jsx').default,
	require('./midi-4.jsx').default,
	require('./midi-5.jsx').default,
	require('./demo-1.jsx').default,
	require('./how-its-made.jsx').default,
	require('./web-component').default,
	require('./web-component-2').default,
	require('./web-component-problems').default,
	require('./my-web-component').default,
	require('./write-to-iframe').default,
	require('./demo-write-to-iframe').default,

	require('./eval').default,
	require('./eval-how-to').default,
	require('./eval-sandboxing').default,

	require('./not-original').default,
	require('./prior-art').default
]
