export default [
	require('./intro.jsx').default,
	require('./me.jsx').default,
	require('./me-pic.jsx').default,
	require('./inspiration.jsx').default,
	require('./break-stuff.jsx').default,
	// require('./idea.jsx').default,
	require('./atari.jsx').default,
	require('./devo.jsx').default,
	require('./modal.jsx').default,
	require('./modular.jsx').default,
	require('./digital-vis-white.jsx').default,
	require('./digital-vis-black.jsx').default,
	require('./web-apis.jsx').default,
	require('./album-art-generator.jsx').default,
	require('./midi-1.jsx').default,
	require('./midi-2.jsx').default,
	require('./midi-3.jsx').default,
	require('./midi-4.jsx').default,
	require('./demo-1.jsx').default
]
